export const FETCH_USER_BY_ID = "FETCH_USER_BY_ID";
export const FETCH_USER_BY_ID_SUCCESS = "FETCH_USER_BY_ID_SUCCESS";
export const FETCH_USER_BY_ID_ERROR = "FETCH_USER_BY_ID_ERROR";
export const FETCH_USER_BY_ID_RESET = "FETCH_USER_BY_ID_RESET";

export const FETCH_ALL_USER = "FETCH_ALL_USER";
export const FETCH_ALL_USER_SUCCESS = "FETCH_ALL_USER_SUCCESS";
export const FETCH_ALL_USER_ERROR = "FETCH_ALL_USER_ERROR";
export const FETCH_ALL_USER_RESET = "FETCH_ALL_USER_RESET";
