export const FETCH_POSTS = "FETCH_POSTS";
export const FETCH_POSTS_SUCCESS = "FETCH_POSTS_SUCCESS";
export const FETCH_POSTS_ERROR = "FETCH_POSTS_ERROR";
export const FETCH_POSTS_RESET = "FETCH_POSTS_RESET";

export const FETCH_POST_BY_ID = "FETCH_POST_BY_ID";
export const FETCH_POST_BY_ID_SUCCESS = "FETCH_POST_BY_ID_SUCCESS";
export const FETCH_POST_BY_ID_ERROR = "FETCH_POST_BY_ID_ERROR";
export const FETCH_POST_BY_ID_RESET = "FETCH_POST_BY_ID_RESET";
