export const FETCH_PHOTO_BY_ID = "FETCH_PHOTO_BY_ID";
export const FETCH_PHOTO_BY_ID_SUCCESS = "FETCH_PHOTO_BY_ID_SUCCESS";
export const FETCH_PHOTO_BY_ID_ERROR = "FETCH_PHOTO_BY_ID_ERROR";
export const FETCH_PHOTO_BY_ID_RESET = "FETCH_PHOTO_BY_ID_RESET";

export const FETCH_ALL_PHOTOS = "FETCH_ALL_PHOTOS";
export const FETCH_ALL_PHOTOS_SUCCESS = "FETCH_ALL_PHOTOS_SUCCESS";
export const FETCH_ALL_PHOTOS_ERROR = "FETCH_ALL_PHOTOS_ERROR";
export const FETCH_ALL_PHOTOS_RESET = "FETCH_ALL_PHOTOS_RESET";

