export const FETCH_COMMENT_BY_ID = "FETCH_COMMENT_BY_ID";
export const FETCH_COMMENT_BY_ID_SUCCESS = "FETCH_COMMENT_BY_ID_SUCCESS";
export const FETCH_COMMENT_BY_ID_ERROR = "FETCH_COMMENT_BY_ID_ERROR";
export const FETCH_COMMENT_BY_ID_RESET = "FETCH_COMMENT_BY_ID_RESET";

export const FETCH_ALL_COMMENTS = "FETCH_ALL_COMMENTS";
export const FETCH_ALL_COMMENTS_SUCCESS = "FETCH_ALL_COMMENTS_SUCCESS";
export const FETCH_ALL_COMMENTS_ERROR = "FETCH_ALL_COMMENTS_ERROR";
export const FETCH_ALL_COMMENTS_RESET = "FETCH_ALL_COMMENTS_RESET";
