export const FETCH_COMMENT_BY_ID = "FETCH_COMMENT_BY_ID";
export const FETCH_COMMENT_BY_ID_SUCCESS = "FETCH_COMMENT_BY_ID_SUCCESS";
export const FETCH_COMMENT_BY_ID_ERROR = "FETCH_COMMENT_BY_ID_ERROR";
export const FETCH_COMMENT_BY_ID_RESET = "FETCH_COMMENT_BY_ID_RESET";
